#ifndef __MKF360_CONFIG_H__
#define __MKF360_CONFIG_H__

#define MKF360_MIC_SAMPLE_RATE_HZ (16000U)
#define MKF360_DMA_FRAME_SAMPLE_NUM (MKF360_MIC_SAMPLE_RATE_HZ / 50U)
#define DFSDM_DMA_FRAME_SAMPLE_NUM (MKF360_MIC_SAMPLE_RATE_HZ / 50U)
#define DAC_DMA_FRAME_SAMPLE_NUM (MKF360_MIC_SAMPLE_RATE_HZ / 50U)
#define IIS_DMA_FRAME_SAMPLE_NUM (MKF360_MIC_SAMPLE_RATE_HZ / 50U)

#endif // !__MKF360_CONFIG_H__